-- ============================================================
-- Fundo Família — schema Supabase (Postgres)
-- Execute este arquivo no SQL Editor do seu projeto Supabase.
-- ============================================================

-- Contribuições (participação das pessoas)
create table if not exists public.contributions (
  id bigint generated by default as identity primary key,
  person_name text not null,
  amount numeric(14, 2) not null default 0,
  contribution_date date not null,
  created_at timestamptz not null default now()
);

-- Operações da B3 (histórico importado do XLSX)
create table if not exists public.b3_operations (
  id bigint generated by default as identity primary key,
  ticker text not null,
  operation_type text not null check (operation_type in ('buy', 'sell')),
  quantity numeric(18, 6) not null,
  unit_price numeric(14, 4) not null,
  total_value numeric(14, 2) not null,
  operation_date date not null,
  source text not null default 'xlsx',
  created_at timestamptz not null default now()
);

-- Posições atuais (fotografia importada do XLSX de posição da B3)
create table if not exists public.positions (
  id bigint generated by default as identity primary key,
  ticker text not null unique,
  type text not null default '',
  quantity numeric(18, 6) not null default 0,
  b3_closing_price numeric(14, 4),
  b3_value numeric(14, 2),
  average_price numeric(14, 4),
  invested_value numeric(14, 2),
  updated_at timestamptz not null default now()
);

-- Ativos (referência: nome, setor e tipo)
create table if not exists public.assets (
  ticker text primary key,
  name text not null default '',
  sector text not null default 'Outros',
  type text not null default ''
);

-- ============================================================
-- RLS: habilita e nega todo acesso direto (anon/authenticated).
-- O servidor do Next.js usa a Service Role Key, que ignora RLS.
-- ============================================================
alter table public.contributions enable row level security;
alter table public.b3_operations enable row level security;
alter table public.positions enable row level security;
alter table public.assets enable row level security;
