-- ============================================================
-- Migração: operações da B3 (negociações — histórico de compras/vendas)
-- Tabela que recebe os dados do XLSX de negociações enviado no /admin
-- ("Importar negociações B3") ou cadastrados manualmente.
-- Execute no SQL Editor do Supabase.
-- ============================================================

create table if not exists public.b3_operations (
  id bigint generated by default as identity primary key,
  ticker text not null,
  operation_type text not null check (operation_type in ('buy', 'sell')),
  quantity numeric(18, 6) not null,
  unit_price numeric(14, 4) not null,
  total_value numeric(14, 2) not null,
  operation_date date not null,
  source text not null default 'xlsx',
  created_at timestamptz not null default now()
);

-- Índice para a consolidação do custo médio (agrupa por ticker, ordena por data).
create index if not exists b3_operations_ticker_date_idx
  on public.b3_operations (ticker, operation_date);

-- RLS: nega todo acesso direto (anon/authenticated).
-- O servidor do Next.js usa a Service Role Key, que ignora RLS.
alter table public.b3_operations enable row level security;
